### ISSUE TITLE
Annouce speakers 

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#82]

**Comment by groovecoder** [comment]
Not sure of the schedule yet, but the talks & speakers are:

## Solve your everyday problems with Genetic Algorithms
When was the last time you wrote an algorithm to plan your diet? As programmers we do amazing things in our everyday job, but rarely do we use our knowledge at home. In this talk I will introduce genetic algorithms and share how I coded a genetic algorithm from scratch and used it to generate my weekly schedule and to create a smart diet planer. We will go through the different stages of the algorithm and understand how they affect the algorithm’s solutions. Let me show you a different side of genetic algorithms and you will discover a new way to solve your everyday problems.
### Mey Beisaron
Mey is a public speaker, a backend developer and a software engineering graduate. When she is not spending her weekends at hackathons, she experiments with algorithms OR learns languages such as russian, french & Clojure. Mey is also a sworn star wars fan. May the force be with you. 

## Understanding Iterators and Iterables in JavaScript
This talk explores the world of iterators and iterables in JavaScript -- aka the backbone of the spread/rest operator, generators, and so much more. Attendees will learn more than the basics: custom iterators will be built and modified and we’ll expand our spread operator knowledge with some unusual uses.
### Jenn Creighton
Jenn Creighton is a software engineer at Rent the Runway and conference speaker. She lives in New York with her two cats, one dog, and maintains a Home for Abandoned Succulents, Mismanaged Plants and Otherwise Ailing Flora. You can find her online @gurlcode. 

## Hack your brain - Ways to improve your thought processes
As developers we are always looking at improving and optimizing our workflows, but why don't we also do that with our thoughts? This talk will explore ways to improve those thought processes through looking at techniques like mindfulness, having a growth mindset, implementing new habits like how you do a sprint and even why speed reading might be for you!
### Christine Seeman
Christine is from Omaha, Nebraska where she works as a full stack Ruby on Rails engineer at Flywheel, WordPress hosting for creatives. She has 12 years experience as a Java software engineer with a focus on APIs and micro-services and took the plunge into Ruby just this May. In her spare time she is an avid long form reader, lover of all true-crime podcasts and is attempting to work through the primary Ashtanga yoga series. 

## APIs: The good the bad the ugly
Service oriented systems have become hugely popular, and the golden age of the monolith has past. Sometimes these services can be fantastic, and other times not so much. Learning how to evaluate APIs and identify problem areas before jumping head first into development can save teams frustration, time, and money. This session will walk through evaluating an API, best practices, and red flags, all from the standpoint of a developer consuming them. No matter your experience level, you'll leave with the skills to effectively tackle your next API.
### Michele Titolo
Michele Titolo is an experienced lead engineer working on Capital at Square. With a career spanning client and server side development, Michele uses her passion for distributed systems to deliver end-user-focused solutions. Outside of work, Michele is a frequent traveler, an advisor to Women Who Code, and an avid Doctor Who fan.
